### ISSUE TITLE
Argument for @NotNull parameter Webstorm 2016.1

### ISSUE THREAD

**Issue by siiron** [idok/scss-lint-plugin#33]
After upgrading to Webstorm 2016.1, the plugin reports the following error whenever a scss-file is changed:

```
Error running ScssLint inspection: Argument for @NotNull parameter 'file' of com/scss/utils/ScssLintRunner.runLint must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'file' of com/scss/utils/ScssLintRunner.runLint must not be null
	at com.scss.utils.ScssLintRunner.runLint(ScssLintRunner.java)
	at com.scss.ScssLintExternalAnnotator.doAnnotate(ScssLintExternalAnnotator.java:257)
	at com.scss.ScssLintExternalAnnotator.doAnnotate(ScssLintExternalAnnotator.java:51)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.c(ExternalToolPass.java:218)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:44)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:267)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:282)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:389)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by seamofreality** [comment]
Having exactly the same problem.

`IllegalArgumentException: Error running ScssLint inspection: Argument for @NotNull parameter 'file' of com/scss/utils/ScssLintRunner.runLint must not be null`

**Comment by bm2u** [comment]
Having **still ** exactly the same problem. Running latest version 1.0.16 with scss_lint (0.47.1) and webstorm 2016.1.

**Comment by idok** [comment]
This [update](https://plugins.jetbrains.com/update/index?pr=&updateId=24878) should be compatible with 2016.1
Please update and report if you have any issues.

**Comment by bm2u** [comment]
@idok well done :+1: Thx!
Sorting Properties   [#34] still fails
