### ISSUE TITLE
"Already disposed: Project (Disposed)" exception.

### ISSUE THREAD

**Issue by extempl** [idok/scss-lint-plugin#38]
Already disposed: Project (Disposed) %PROJECTNAME%
    java.lang.AssertionError: Already disposed: Project (Disposed)  %PROJECTNAME%
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:265)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:52)
	at com.intellij.openapi.components.ServiceKt.getStateStore(service.kt:29)
	at com.intellij.openapi.project.impl.ProjectImpl.getStateStore(ProjectImpl.java:194)
	at com.intellij.openapi.project.impl.ProjectImpl.getBaseDir(ProjectImpl.java:226)
	at com.wix.files.ThreadLocalTempActualFile.getTempDir(ThreadLocalTempActualFile.java:105)
	at com.wix.files.ThreadLocalTempActualFile.createFile(ThreadLocalTempActualFile.java:124)
	at com.wix.files.ThreadLocalTempActualFile.getOrCreateFile(ThreadLocalTempActualFile.java:49)
	at com.wix.files.ActualFileManager.getOrCreateActualFile(ActualFileManager.java:40)
	at com.scss.ScssLintExternalAnnotator.doAnnotate(ScssLintExternalAnnotator.java:270)
	at com.scss.ScssLintExternalAnnotator.doAnnotate(ScssLintExternalAnnotator.java:53)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.c(ExternalToolPass.java:218)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:44)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:267)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:282)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:389)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Happens 86 times since project start.

**Comment by Glutnix** [comment]
Also just got this: 

```
Already disposed: Project (Disposed) ticketing-cms
java.lang.AssertionError: Already disposed: Project (Disposed) ticketing-cms
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:259)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:52)
	at com.intellij.openapi.components.ServiceKt.getStateStore(service.kt:29)
	at com.intellij.openapi.project.impl.ProjectImpl.getStateStore(ProjectImpl.java:199)
	at com.intellij.openapi.project.impl.ProjectImpl.getBaseDir(ProjectImpl.java:233)
	at com.wix.files.ThreadLocalTempActualFile.getTempDir(ThreadLocalTempActualFile.java:105)
	at com.wix.files.ThreadLocalTempActualFile.createFile(ThreadLocalTempActualFile.java:124)
	at com.wix.files.ThreadLocalTempActualFile.getOrCreateFile(ThreadLocalTempActualFile.java:49)
	at com.wix.files.ActualFileManager.getOrCreateActualFile(ActualFileManager.java:40)
	at com.scss.ScssLintExternalAnnotator.doAnnotate(ScssLintExternalAnnotator.java:270)
	at com.scss.ScssLintExternalAnnotator.doAnnotate(ScssLintExternalAnnotator.java:53)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.d(ExternalToolPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:44)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:260)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:274)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:229)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:222)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:389)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.runFirstTaskThenPollAndRunRest(BoundedTaskExecutor.java:178)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$000(BoundedTaskExecutor.java:40)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:197)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by daviddelusenet** [comment]
Also have this bug.

**Comment by Amit1487** [comment]
Any resolution to above bug..i am also facing this issue

**Comment by Viktor-Bredihin** [comment]
same here, it's annoying
